version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    image: ghcr.io/tikelespike/nilee:main
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data: